spring.application.name=jobms
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/job
spring.datasource.username=Test
spring.datasource.password=Test
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

